---
  #########
  # PATHS #
  #########
  data: '/home/sanch046/lustre/ML-on-LPMOs/data'
  CAZy_downloadable_files: '/home/sanch046/lustre/ML-on-LPMOs/data/CAZy_downloadable_files'
  CAZy_characterized:  '/home/sanch046/lustre/ML-on-LPMOs/data/CAZy_characterized'
  CAZy_structures:  '/home/sanch046/lustre/ML-on-LPMOs/data'
  CAZy_expanded:  '/home/sanch046/lustre/ML-on-LPMOs/data/CAZy_expanded'

  supervised: '/home/sanch046/lustre/ML-on-LPMOs/data/supervised'
  plots: '/home/sanch046/lustre/ML-on-LPMOs/docs/plots'

  AF_all: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_all'
  AF_labels: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_labels'
  AF_labels_core: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_labels_core'
  AF_his1: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_his1'
  AF_cif: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_cif'
  AF_pae: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_pae'
  DPAM_results: '/home/sanch046/lustre/ML-on-LPMOs/data/DPAM_results'
  DPAM_tool: '/home/sanch046/lustre/DPAM'
  AF_core: '/home/sanch046/lustre/ML-on-LPMOs/data/AF_core'
  SignalP: '/home/sanch046/lustre/ML-on-LPMOs/data/SignalP'
  InterPro: '/home/sanch046/lustre/ML-on-LPMOs/data/InterPro'
  FASTA: '/home/sanch046/lustre/ML-on-LPMOs/data/FASTA'
  
  family2color:
    AA0: '#e377c2'
    AA9: '#1f77b4'
    AA10: '#ff7f0e'
    AA11: '#2ca02c'
    AA13: '#d62728'
    AA14: '#9467bd'
    AA15: '#8c564b'
    AA16: '#e377c2'
    AA17: '#bcbd22'

  ML: '/home/sanch046/lustre/ML-on-LPMOs/data/ML'
  pymol: '/home/sanch046/lustre/ML-on-LPMOs/data/pymol'
